FROM ubuntu:mantic

COPY .devcontainer/sources.cn /etc/apt/sources.list

RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y cmake git curl zip unzip tar
RUN apt-get install -y gcc-12 g++-12
RUN apt-get install -y gdb

WORKDIR /usr/bin
# RUN ln -s gcc-12 gcc
RUN ln -s g++-12 g++

WORKDIR /usr/local
RUN git clone --depth=1 https://github.com/Microsoft/vcpkg.git && \
    ./vcpkg/bootstrap-vcpkg.sh
ENV VCPKG_ROOT /usr/local/vcpkg
ENV PATH $VCPKG_ROOT:$PATH

RUN apt-get install -y pkg-config 
RUN apt-get install -y python3
RUN vcpkg install catch2
RUN vcpkg install pistache
# RUN vcpkg install boost